+ -m flag to comment out URLs successfully downloaded

diff --git a/dlvids b/dlvids
--- a/dlvids
+++ b/dlvids
@@ -1,29 +1,71 @@
 #!/bin/bash
 
+### Colors
+txtred='\e[0;31m' # Red
+txtgrn='\e[0;32m' # Green
+txtylw='\e[0;33m' # Yellow
+txtblu='\e[0;34m' # Blue
+txtpur='\e[0;35m' # Purple
+txtcyn='\e[0;36m' # Cyan
+txtwht='\e[0;37m' # White
+txtrst='\e[0m'    # Text Reset
+###
+
+if [[ $1 == "-m" ]]; then
+    modify=true
+    shift
+else
+    modify=false
+fi
+
 if [[ -n $1 ]]; then
     inputFile="$1"
 else
-    echo -e "Usage: $(basename $0) FILE\n
+	echo -e "${txtred}Usage: $(basename $0) FILE${txtrst}\n
 FILE: a file with one URL per line,\nlines starting with '#'\
  are ignored"
     exit 1
 fi
 
 if [[ ! -e $inputFile ]]; then
-    echo "Input file not found: $inputFile"
+    echo -e "${txtred}Input file not found: $inputFile${txtrst}"
     exit 1
 fi
 
 processed=0
 skipped=0
+errors=0
 
 while read -r url || [[ -n "$url" ]]; do
     if [[ ${url:0:1} != "#" ]]; then
-        yt "$url"
-        processed=$(( $processed + 1 ))
+        youtube-dl "$url";
+        status=$?
+        if test $status; then
+           processed=$(( $processed + 1 ))
+           if $modify; then
+               sed -i 's|^\('$url'\)$|#\1|' $inputFile
+           fi
+        else
+            errors=$(( $errors + 1 ))
+        fi
     else
         skipped=$(($skipped + 1 ))
     fi
 done < $inputFile
 
-echo -e "$processed URLs processed, $skipped skipped."
+processedMsg="$processed URL processed"
+if [[ $processed != 0 ]]; then
+	processedMsg=${txtgrn}${processedMsg}${txtrst};
+fi
+if [[ $skipped != 0 ]]; then
+	skippedMsg=", $skipped skipped";
+fi
+if [[ $errors != 0 ]]; then
+	errorsMsg=", ${txtred}$errors errors${txtrst}";
+	returnVal=1;
+else
+	returnVal=0;
+fi
+
+echo -e "$processedMsg$skippedMsg$errorsMsg."
+exit $returnVal
